name: Build, Test and Publish
on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - 'master'
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  BuildNumber: ${{ github.run_number }}
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.13.0-chrome78-ff70
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: app
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      OrchardCore__ConnectionString: "User ID=postgres;Password=admin;Host=postgres;Port=5432;Database=app;"
      OrchardCore__DatabaseProvider: "Postgres"
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402
    - name: Test
      run: |
           cd test/cypress
           npm install
           npm run ci:test
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: functional-test-postgresql-failure
        path: |
          test/cypress/screenshots
          src/StatCan.OrchardCore.Cms.Web/App_Data/logs
        retention-days: 3
  publish:
    if: github.ref == 'refs/heads/master'
    needs: test
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.402
      - name: Dotnet build 
        run: dotnet build -c Release
      - name: Pack
        run: dotnet pack -c Release -o build-output --no-build
      - name: Publish nuget
        run: dotnet nuget push './build-output/*.nupkg' -k ${{secrets.NUGET_APIKEY}} -n true -s https://nuget.cloudsmith.io/statcan-digitalinnovation/statcan-orchardcore/v3/index.json  --skip-duplicate
